### ISSUE TITLE
Malloc error: pointer being freed was not allocated

### ISSUE THREAD

**Issue by cant-access-rediska0123** [refresh-bio/colord#6]
Hi!

I tried to run this tool on Mac OS (Monterey) and have problems running provided test examples.

I had some problems with `conda` on my computer, so I compiled it myself. 

Running `make` resulted in `clang: error: unsupported option '-static-libgcc'`. After I deleted this flag from Makefile it compiled. When I tried to test it using your instructions, I got this error:

```
> ./colord compress-ont ./../test/M.bovis.fastq ont.default 
colord(28784,0x1064c6600) malloc: *** error for object 0xb43ac010120: pointer being freed was not allocated
colord(28784,0x1064c6600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ./colord compress-ont ./../test/M.bovis.fastq ont.default
```

I have the same problem for all other test examples.

Is there anything you can suggest? Thanks in advance

**Comment by marekkokot** [comment]
Hi,

thanks for reporting this!
I think I have fixed that. Could you please try again?
Use `git clone --recurse-submodules https://github.com/refresh-bio/colord` to get a fresh clone.
I would really appreciate the feedback.

**Comment by cant-access-rediska0123** [comment]
This helped, now the examples work fine. Thanks!
